"""Rut pacienet como campo unico

Revision ID: 1426438c9a1e
Revises: e887f45313c7
Create Date: 2024-12-02 21:37:40.275680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1426438c9a1e'
down_revision = 'e887f45313c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paciente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rut', sa.String(length=12), nullable=False))
        batch_op.create_unique_constraint('uq_paciente_rut', ['rut'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paciente', schema=None) as batch_op:
        batch_op.drop_constraint('uq_paciente_rut', type_='unique')
        batch_op.drop_column('rut')

    # ### end Alembic commands ###
