"""apellido medico

Revision ID: b609f1145484
Revises: cbe63ce20fbb
Create Date: 2024-11-07 19:49:54.008514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b609f1145484'
down_revision = 'cbe63ce20fbb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medico', schema=None) as batch_op:
        batch_op.add_column(sa.Column('apellido', sa.String(length=64), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medico', schema=None) as batch_op:
        batch_op.drop_column('apellido')

    # ### end Alembic commands ###
