"""Tablas Paciente Medico Horario y Cita

Revision ID: cbe63ce20fbb
Revises: 
Create Date: 2024-11-06 19:50:29.248723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbe63ce20fbb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medico',
    sa.Column('id_medico', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=64), nullable=False),
    sa.Column('especialidad', sa.String(length=64), nullable=False),
    sa.Column('telefono', sa.String(length=15), nullable=True),
    sa.PrimaryKeyConstraint('id_medico')
    )
    op.create_table('paciente',
    sa.Column('id_paciente', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=64), nullable=False),
    sa.Column('apellido', sa.String(length=64), nullable=False),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('telefono', sa.String(length=15), nullable=True),
    sa.PrimaryKeyConstraint('id_paciente')
    )
    with op.batch_alter_table('paciente', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_paciente_email'), ['email'], unique=True)

    op.create_table('horario',
    sa.Column('id_horario', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('bloque', sa.Enum('BLOQUE_1', 'BLOQUE_2', 'BLOQUE_3', 'BLOQUE_4', 'BLOQUE_5', 'BLOQUE_6', 'BLOQUE_7', 'BLOQUE_8', 'BLOQUE_9', 'BLOQUE_10', 'BLOQUE_11', 'BLOQUE_12', 'BLOQUE_13', 'BLOQUE_14', 'BLOQUE_15', 'BLOQUE_16', 'BLOQUE_17', 'BLOQUE_18', name='bloquehorario'), nullable=False),
    sa.Column('id_medico', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_medico'], ['medico.id_medico'], ),
    sa.PrimaryKeyConstraint('id_horario')
    )
    op.create_table('cita',
    sa.Column('id_cita', sa.Integer(), nullable=False),
    sa.Column('id_paciente', sa.Integer(), nullable=False),
    sa.Column('id_medico', sa.Integer(), nullable=False),
    sa.Column('id_horario', sa.Integer(), nullable=False),
    sa.Column('estado', sa.Enum('AGENDADA', 'CONFIRMADA', 'REALIZADA', 'CANCELADA', 'NO_ASISTIO', name='estadocita'), nullable=False),
    sa.ForeignKeyConstraint(['id_horario'], ['horario.id_horario'], ),
    sa.ForeignKeyConstraint(['id_medico'], ['medico.id_medico'], ),
    sa.ForeignKeyConstraint(['id_paciente'], ['paciente.id_paciente'], ),
    sa.PrimaryKeyConstraint('id_cita')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cita')
    op.drop_table('horario')
    with op.batch_alter_table('paciente', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_paciente_email'))

    op.drop_table('paciente')
    op.drop_table('medico')
    # ### end Alembic commands ###
